version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shoe_shop_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/shoe_shop_db.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

  webserver:
    build:
      context: ./php-apache2
      dockerfile: Dockerfile
    container_name: apache-server
    ports:
      - "9000:80"
    volumes:
      - app-code:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  app:
    image: pquyenn/test-sis:latest
    # build:
    #   context: ./src
    #   dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - app-code:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - app-network

volumes:
  app-code:

networks:
  app-network:
    driver: bridge
